source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'rake','0.8.7'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '2.3.16'
gem 'json', '1.5.0'
gem 'settingslogic'
gem 'fastercsv'
gem 'rest-client','1.6.3'
gem 'mechanize'
gem 'mysql2'
gem 'mysql'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'paginate', '1.0.1'
gem 'mime-types', '1.19'
gem 'nokogiri', '1.5.2'
gem 'rcov'
gem 'passenger'
